### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by cmcd146** [cmcd146/Readwell-Full-Stack#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by evhumphrey** [comment]
Looks good! 

Some feedback: 

- [x] I would center the form to look something like
![screen shot 2018-10-11 at 5 33 04 pm](https://user-images.githubusercontent.com/6361824/46841287-d0a5d300-cd7b-11e8-8fdf-5d48ae54d20d.png)
- [x] I would also have some content on the home page (it looks a little barren). Check out: https://readbooksapp.herokuapp.com/#/ (maybe the "Meet your next favorite book"), and a the text "New here? Create a free account!" and a button that links to your sign up form.

Let me know if you have questions on this!

**Comment by cmcd146** [comment]
Alright, it should be better now.  It took me forever to figure out my react routes, but now you can't get the splash page while being signed in.  I have a dummy home page for users who are signed in which I will build off of in the next MVP.
